dist: bionic
before_install:
- openssl aes-256-cbc -K $encrypted_cfb2f4d2da43_key -iv $encrypted_cfb2f4d2da43_iv
  -in my.conf.enc -out my.conf -d
- sudo apt update
- sudo apt install vpnc
language: minimal
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
